name: Read Text File on the main branch

on:
  push: 
    branches:
      - main
    paths:
      - 'test.txt' # specify the path to the text file
jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Run the python file
        run: |
          python add.py
      
